import React, { useEffect, useState } from "react";
//
import Layout from "../../../common/layout";
import ListTable from "../../../../elements/list/list";
import { Container } from "../../../common/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file

const DeliveryMan = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Delivery Man - Diet Food Management Portal`;
  }, []);

  const [attributes] = useState([
    // {
    //   type: "text",
    //   placeholder: "User Name",
    //   name: "username",
    //   validation: "",
    //   default: "",
    //   label: "User Name",
    //   required: true,
    //   view: true,
    //   add: true,
    //   update: true,
    // },
    {
      type: "text",
      placeholder: "Employee ID",
      name: "employeeID",
      validation: "",
      default: "",
      label: "Employee ID",
      required: false,
      view: true,
      add: false,
      update: false,
    },
    {
      type: "text",
      placeholder: "Name",
      name: "userDisplayName",
      validation: "",
      default: "",
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Gender",
      name: "gender",
      validation: "",
      default: "",
      tag: true,
      label: "Gender",
      showItem: "Gender",
      required: true,
      view: false,
      filter: false,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Male,Female",
    },
    {
      type: "email",
      placeholder: "E-Mail",
      name: "email",
      validation: "",
      default: "",
      tag: true,
      label: "E-Mail",
      required: true,
      view: true,
      add: true,
      update: false,
    },
    {
      type: "select",
      placeholder: "Gender",
      name: "subscriber",
      validation: "",
      default: "",
      tag: true,
      label: "Gender",
      showItem: "gender",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      // apiType: "CSV",
      // selectApi: "Male,Female",
    },

    // {
    //   type: "date",
    //   apiType: "API",
    //   selectApi: "",
    //   placeholder: "DOB",
    //   name: "subscriber",
    //   validation: "",
    //   showItem: "dateOfBirth",
    //   default: "",
    //   tag: true,
    //   label: "DOB",
    //   required: true,
    //   view: true,
    //   add: false,
    //   update: false,
    // },
    // {
    //   type: "date",
    //   placeholder: "YYYY/MM/DD",
    //   name: "dateOfBirth",
    //   validation: "",
    //   default: "",
    //   tag: true,
    //   label: "DOB",
    //   required: true,
    //   view: false,
    //   add: true,
    //   update: true,
    // },
    {
      type: "password",
      placeholder: "password",
      name: "password",
      validation: "",
      default: "",
      // tag: true,
      label: "password",
      required: true,
      view: true,
      add: true,
      update: false,
    },
    // {
    //   type: "textarea",
    //   apiType: "",
    //   selectApi: "",
    //   placeholder: "Address",
    //   name: "subscriber",
    //   // collection: "subscribers",
    //   validation: "",
    //   showItem: "address",
    //   default: "",
    //   tag: true,
    //   label: "Address",
    //   required: true,
    //   view: true,
    //   add: false,
    //   update: false,
    // },
    // {
    //   type: "textarea",
    //   apiType: "",
    //   selectApi: "",
    //   placeholder: "Address",
    //   name: "address",
    //   validation: "",
    //   showItem: "address",
    //   default: "",
    //   tag: true,
    //   label: "Address",
    //   required: true,
    //   view: false,
    //   add: true,
    //   update: true,
    // },
    {
      type: "textarea",
      apiType: "",
      selectApi: "",
      placeholder: "Address",
      name: "address",
      collection: "subscriber",
      validation: "",
      showItem: "address",
      default: "",
      tag: true,
      label: "Address",
      required: true,
      view: true,
      add: true,
      update: false,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "deliveryman-location/select",
      placeholder: "Location",
      name: "deliveryManLocation",
      collection: "",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Location",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "vehicle-category/select",
      placeholder: "Vehicle",
      name: "vehicleType",
      collection: "",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Vehicle",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "Image",
      name: "userImage",
      validation: "",
      default: "",
      tag: true,
      label: "Image",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Identity Type",
      name: "identityType",
      validation: "",
      default: "",
      tag: false,
      label: "Identity Type",
      required: true,
      view: true,
      add: true,
      update: true,
      selectApi: "Passport, License",
      apiType: "CSV",
    },
    {
      type: "image",
      placeholder: "Identity Doc",
      name: "identityDocument",
      validation: "",
      default: "",
      tag: true,
      label: "Identity Doc",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Identity Number",
      name: "identityNumber",
      validation: "",
      default: "",
      label: "Identity Number",
      required: true,
      view: true,
      add: true,
      update: true,
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={`user`}
        displayColumn="double"
        // itemTitle={`userDisplayName`}
        itemTitle={{ name: "userDisplayName", type: "text", collection: "" }}
        shortName={`Delivery Man`}
        parentReference={"userType"}
        referenceId={"64815bde89e0a44fc31c53b0"}
        // formMode={`single`}
        formMode={`double`}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
export default Layout(DeliveryMan);
