import React, { useEffect, useState } from "react";
import Layout from "../../../common/layout";
import ListTable from "../../../../elements/list/list";
import { Container } from "../../../common/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const Ingredient = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Ingredient - Diet Food Management Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "text",
      placeholder: "Ingredient",
      name: "ingredientsName",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Ingredient",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Calories",
      name: "calories",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Calories",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Protein",
      name: "protein",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Protein",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "SatFat",
      name: "satFat",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "SatFat",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "UnSatFat",
      name: "unSatFat",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "UnSatFat",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "TotalFat",
      name: "totalFat",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "TotalFat",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Cholesterol",
      name: "cholesterol",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Cholesterol",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Fiber",
      name: "fiber",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Fiber",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Carbohydrate",
      name: "carbohydrate",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Carbohydrate",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Sugar",
      name: "sugars",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Sugar",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Iron",
      name: "iron",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Iron",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Calcium",
      name: "calcium",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Calcium",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    // {
    //   type: "select",
    //   apiType: "API",
    //   selectApi: "variant-group/select",
    //   placeholder: "Varient Group",
    //   name: "varientGroup",
    //   validation: "",
    //   showItem: "variantGroupName",
    //   default: "",
    //   tag: true,
    //   label: "Varient Group",
    //   required: true,
    //   view: true,
    //   add: true,
    //   update: true,
    //   filter: false,
    // },
    // {
    //   type: "select",
    //   apiType: "API",
    //   selectApi: "variant-level/select",
    //   placeholder: "varientLevel",
    //   name: "varientLevel",
    //   validation: "",
    //   showItem: "variantLevelName",
    //   default: "",
    //   tag: true,
    //   label: "varientLevel",
    //   required: true,
    //   view: true,
    //   add: true,
    //   update: true,
    //   filter: false,
    // },
    {
      type: "text",
      placeholder: "Quantity",
      name: "quantity",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Quantity",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Vitamin A",
      name: "VitaminA",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Vitamin A",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Vitamin C",
      name: "vitaminC",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Vitamin C",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Vitamin E",
      name: "vitaminE",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Vitamin E",
      required: true,
      view: true,
      add: true,
      update: true,
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        // api={`recipe-ingredients`}
        api={`ingredient`}
        // itemTitle={`label`}
        itemTitle={{
          name: "ingredientsName",
          type: "text",
          collection: "",
        }}
        shortName={`Ingredient Management`}
        // formMode={`single`}
        formMode={`double`}
        //
        {...props}
        // Additional attributes related to the menu
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
// exporting the page with parent container layout..
export default Layout(Ingredient);
