import React, { useEffect, useState } from "react";
import moment from "moment";
//
import Layout from "../../../common/layout";
import ListTable from "../../../../elements/list/list";
import { Container } from "../../../common/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file

const Dietitian = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Dietitian - Diet Food Management Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "text",
      placeholder: "Employee ID",
      name: "employeeID",
      validation: "",
      default: "",
      label: "Employee ID",
      required: false,
      view: true,
      add: false,
      update: false,
    },
    {
      type: "text",
      placeholder: "Name",
      name: "userDisplayName",
      validation: "",
      default: "",
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Gender",
      name: "subscriber",
      validation: "",
      default: "",
      tag: true,
      label: "Gender",
      showItem: "gender",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      // apiType: "CSV",
      // selectApi: "Male,Female",
    },
    {
      type: "select",
      placeholder: "Gender",
      name: "gender",
      validation: "",
      default: "",
      tag: true,
      label: "Gender",
      showItem: "Gender",
      required: true,
      view: false,
      filter: false,
      add: true,
      update: false,
      apiType: "CSV",
      selectApi: "Male,Female",
    },
    {
      type: "email",
      placeholder: "E-Mail",
      name: "email",
      validation: "",
      default: "",
      tag: true,
      label: "E-Mail",
      required: true,
      view: true,
      add: true,
      update: false,
    },
    {
      type: "password",
      placeholder: "password",
      name: "password",
      validation: "",
      default: "",
      // tag: true,
      label: "password",
      required: true,
      view: false,
      add: true,
      update: false,
    },
    {
      type: "title",
      title: "Email and password are required for login",
      name: "bmr",
      add: true,
      update: true,
    },
    {
      type: "textarea",
      apiType: "",
      selectApi: "",
      placeholder: "Address",
      name: "address",
      collection: "subscriber",
      validation: "",
      showItem: "address",
      default: "",
      tag: true,
      label: "Address",
      required: true,
      view: true,
      add: true,
      update: false,
    },
    {
      type: "text",
      placeholder: "MOH License",
      name: "mohLicense",
      validation: "",
      default: "",
      label: "MOH License",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
    },
    // {
    //   type: "date",
    //   placeholder: "License Validity",
    //   name: "licenseValidity",
    //   validation: "",
    //   default: "",
    //   label: "License Validity",
    //   tag: true,
    //   required: true,
    //   view: true,
    //   add: true,
    //   update: true,
    // },
    {
      type: "date",
      placeholder: "License Validitys",
      name: "licenseValidity",
      showItem: "",
      collection: "",
      validation: "",
      minDate: moment().subtract(70, "years").toDate(),
      default: moment().toDate(),
      tag: true,
      label: "License Validitys",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "textarea",
      placeholder: "Speciality",
      name: "speciality",
      validation: "",
      default: "",
      label: "Speciality",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "textarea",
      placeholder: "Qualification",
      name: "qualification",
      validation: "",
      default: "",
      label: "Qualification",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "nationality/select",
      placeholder: "Nationality",
      name: "nationality",
      collection: "nationality",
      showItem: "nationality",
      validation: "",
      default: "",
      tag: true,
      label: "Nationality",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "diet-centre-branch/select",
      placeholder: "Diet Centre Branch",
      name: "branchName",
      collection: "branchName",
      showItem: "name",
      validation: "",
      default: "",
      tag: true,
      label: "Diet Centre Branch",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    {
      type: "image",
      placeholder: "Image",
      name: "userImage",
      validation: "",
      default: "",
      tag: true,
      label: "Image",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Status",
      name: "status",
      validation: "",
      default: "",
      tag: true,
      label: "Status",
      showItem: "status",
      required: true,
      view: true,
      filter: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Active,Leave,Resigned,Terminated",
    },
  ]);

  const [daySlot] = useState([
    {
      type: "select",
      placeholder: "Day",
      name: "day",
      validation: "",
      default: "",
      tag: true,
      label: "Day",
      showItem: "",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
    },
    {
      type: "select",
      placeholder: "Slot",
      name: "availableSlots",
      validation: "",
      default: "",
      label: "Slot",
      tag: true,
      showItem: "",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi:
        "9:00 AM - 11:00 AM ,11:00 AM - 12:00 AM, 2:00 PM - 3:00 PM, 3:00 PM - 4:00 PM",
    },
    // {
    //   type: "text",
    //   placeholder: "Slot",
    //   name: "availableSlots",
    //   validation: "",
    //   default: "",
    //   label: "Slot",
    //   tag: true,
    //   required: true,
    //   view: true,
    //   add: true,
    //   update: true,
    // },
    {
      type: "text",
      placeholder: "Max Booking Slots",
      name: "maxBookingsPerSlot",
      validation: "",
      default: "",
      label: "Max Booking Slots",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
    },
  ]);

  const [resetPassword] = useState([
    {
      type: "text",
      placeholder: "New Password",
      name: "newPassword",
      validation: "",
      default: "",
      label: "New Password",
      required: true,
      view: true,
      add: true,
      update: true,
    },
  ]);

  const [actions] = useState([
    {
      element: "button",
      type: "subList",
      id: "appointment",
      // itemTitle: "username",
      itemTitle: {
        name: "day",
        type: "text",
        collection: "",
      },
      title: "Slots",
      attributes: daySlot,
      params: {
        api: `day-slot`,
        parentReference: "dietician",
        // itemTitle: "username",
        itemTitle: {
          name: "day",
          type: "text",
          collection: "",
        },
        shortName: "Slots",
        addPrivilege: true,
        delPrivilege: false,
        updatePrivilege: false,
        customClass: "medium",
        formMode: "double",
      },
    },
    {
      element: "button",
      type: "subList",
      id: "appointment",
      // itemTitle: "username",
      itemTitle: {
        name: "username",
        type: "text",
        collection: "dietician",
      },
      title: "Reset Password",
      attributes: resetPassword,
      params: {
        api: `auth/update-passoword`,
        parentReference: "user",
        // itemTitle: "username",
        itemTitle: {
          name: "username",
          type: "text",
          collection: "dietician",
        },
        shortName: "Reset Password",
        addPrivilege: true,
        delPrivilege: true,
        updatePrivilege: true,
        customClass: "medium",
        formMode: "double",
      },
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        actions={actions}
        api={`user`}
        displayColumn="single"
        // itemTitle={`userDisplayName`}
        itemTitle={{ name: "userDisplayName", type: "text", collection: "" }}
        shortName={`Dietitian`}
        parentReference={"userType"}
        referenceId={"6471b34d9fb2b29fe0458878"}
        // formMode={`single`}
        formMode={`double`}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
export default Layout(Dietitian);
