import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
//
import Layout from "../../common/layout";
import ListTable from "../../../elements/list/list";
import { Container } from "../../common/layout/styels";
import PopupView from "../../../elements/popupview";
import AvailableCaloriesCustom from "./avialableCalories/availableCaloriesCustom";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file

const AvailableCalories = (props) => {
  const [openMenuSetup, setOpenMenuSetup] = useState(false);
  const [openItemData, setOpenItemData] = useState(null);

  // Function to close the SetupMenu popup
  const closeModal = () => {
    setOpenMenuSetup(false);
    setOpenItemData(null);
  };
  //to update the page title
  useEffect(() => {
    document.title = `FoodExchnage Calories - Diet Food Management Portal`;
  }, []);

  const themeColors = useSelector((state) => state.themeColors);

  const [attributes] = useState([
    {
      type: "select",
      placeholder: "Calories",
      name: "calories",
      validation: "",
      default: "0",
      tag: false,
      label: "Calories",
      required: true,
      view: true,
      add: true,
      update: true,
      selectApi: [
        
        { id: 1200, value: "1200" },
        { id: 1300, value: "1300" },
        { id: 1400, value: "1400" },
        { id: 1500, value: "1500" },
        { id: 1600, value: "1600" },
        { id: 1700, value: "1700" },
        { id: 1800, value: "1800" },
        { id: 1900, value: "1900" },
        { id: 2000, value: "2000" },
        { id: 2100, value: "2100" },
        { id: 2200, value: "2200" },
        { id: 2300, value: "2300" },
        { id: 2400, value: "2400" },
        { id: 2500, value: "2500" },
        { id: 2600, value: "2600" },
        { id: 2700, value: "2700" },
        { id: 2800, value: "2800" },
        { id: 2900, value: "2900" },
        { id: 3000, value: "3000" },
      ],
      apiType: "JSON",
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "mealtime-category/select",
      placeholder: "Mealtime Category",
      name: "mealTimeCategory",
      validation: "",
      showItem: "mealtimeCategoriesName",
      default: "0",
      tag: true,
      label: "Mealtime Category",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "diet/select",
      placeholder: "Diet",
      name: "diet",
      validation: "",
      showItem: "title",
      default: "0",
      tag: true,
      label: "Diet",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    // TYPE OF DIET IS A DIET //
    // DIET PLAN IS A SUB DIET //
    {
      type: "select",
      apiType: "API",
      selectApi: "sub-diet/get-sub-diet-by-diet",
      updateOn: "diet",
      placeholder: "Sub Diet",
      name: "subDiet",
      validation: "",
      showItem: "title",
      collection: "subDiet",
      default: "0",
      tag: true,
      label: "Sub Diet",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
     {
      type: "select",
      placeholder: "Category",
      name: "category",
      validation: "",
      tag: true,
      default: "General",
      filter: true,
      label: "Category",
      required: true,
      view: true,
      add: true,
      update: true,
      selectApi: [
       
        { id: "FoodExchange", value: "Food Exchange Diet" },
      ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Starch",
      name: "starch",
      validation: "",
      tag: true,
      default: "0",
      label: "Starch",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Lean Meat",
      name: "leanMeat",
      validation: "",
      tag: true,
      default: "0",
      label: "Lean Meat",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Skim Milk",
      name: "skimMilk",
      validation: "",
      tag: true,
      default: "0",
      label: "Skim Milk",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Non-Starchy Vegetable",
      name: "nonStarchyVegetable",
      validation: "",
      tag: true,
      default: "0",
      label: "Non-Starchy Vegetable",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Fruits",
      name: "fruits",
      validation: "",
      tag: true,
      default: "0",
      label: "Fruits",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Fats",
      name: "fats",
      validation: "",
      tag: true,
      default: "0",
      label: "Fats",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Sugar",
      name: "sugar",
      validation: "",
      tag: true,
      default: "0",
      label: "Sugar",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Very Lean Meat",
      name: "veryLeanMeat",
      validation: "",
      tag: true,
      default: "0",
      label: "Very Lean Meat",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Medium Fat Meat / Egg",
      name: "mediumFatMeat",
      validation: "",
      tag: true,
      default: "0",
      label: "Medium Fat Meat / Egg",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "High Fat Meat",
      name: "highFatMeat",
      validation: "",
      tag: true,
      default: "0",
      label: "High Fat Meat",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Vegetarian Protein",
      name: "vegetarianProtein",
      validation: "",
      tag: true,
      default: "0",
      label: "Vegetarian Protein",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Low Fat Milk",
      name: "lowfatMilk",
      validation: "",
      tag: true,
      default: "0",
      label: "Low Fat Milk",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Regular Milk",
      name: "regularMilk",
      validation: "",
      tag: true,
      default: "0",
      label: "Regular Milk",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    },
    {
      type: "select",
      placeholder: "Other",
      name: "other",
      validation: "",
      tag: true,
      default: "0",
      label: "Other",
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
    selectApi: [
    { id: 0, value: "0" },
    { id: 1, value: "1" },
    { id: 2, value: "2" },
    { id: 3, value: "3" },
    { id: 4, value: "4" },
    { id: 5, value: "5" },
    { id: 6, value: "6" },
    { id: 7, value: "7" },
    { id: 8, value: "8" },
    { id: 9, value: "9" },
    { id: 10, value: "10" },
    { id: 11, value: "11" },
    { id: 12, value: "12" },
    { id: 13, value: "13" },
    { id: 14, value: "14" },
    { id: 15, value: "15" },
  ],
      apiType: "JSON",
    }
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={`available-calories`}
        displayColumn="double"
        // itemTitle={`userDisplayName`}
        itemTitle={{ name: "calories", type: "text", collection: "" }}
        shortName={`Food Exchange  Calories`}
        // parentReference={"userType"}
        // referenceId={"64815bde89e0a44fc31c53b0"}
        formMode={`double`}
        viewMode="table"
        // formMode={`double`}
        {...props}
        attributes={attributes}
      ></ListTable>
      {openMenuSetup && openItemData && (
        <PopupView
          // Popup data is a JSX element which is binding to the Popup Data Area like HOC
          popupData={
            <AvailableCaloriesCustom
              openData={openItemData}
              setMessage={props.setMessage}
              // Pass selected item data (Menu Title) to the popup for setting the time
            />
          }
          themeColors={themeColors}
          closeModal={closeModal}
          itemTitle={{ name: "title", type: "text", collection: "" }}
          openData={openItemData} // Pass selected item data to the popup for setting the time and taking menu id and other required data from the list item
          customClass={"large"}
        ></PopupView>
      )}
    </Container>
  );
};
export default Layout(AvailableCalories);
